server:
  port: 8110 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db191125_guli_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456789
  jackson:
    time-zone: GMT+8 #东八区
    date-format: yyyy-MM-dd HH:mm:ss #日期显示格式
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.237:8848
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#service-oss:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 0 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 1000 #连接建立的超时时长，默认1秒
  ReadTimeout: 1000 #处理请求的超时时间，默认为1秒


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml
feign:
  sentinel:
    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 1000 #连接建立的超时时长，默认1秒
#        readTimeout: 1000 #处理请求的超时时间，默认为1秒
