server:
  port: 8160 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-ucenter # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.237:8848
  #spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db191125_guli_ucenter?serverTimezone=GMT%2B8
    username: root
    password: 123456789

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/ucenter/mapper/xml/*.xml
