server:
  port: 8150 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.205:8848
  #spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#腾讯云短信
tengxun:
  sms:
    secretId: AKIDQghSwDF0UhdIgofHchW5NO8bniMiqhGY
    secretKey: 3pJWT9YfV6QTEjxub2B3ey1nIWT9YfW6
    #短信应用 ID
    appid: 1312068389
    #短信签名内容
    sign: 463889
    #短信模板ID
    templateID: 1411210
    smsSdkAppId: 1400682889


aliyun:
  sms:
    regionId: cn-shanghai
    keyId: LTAI5tMhVTR4YCguKhMvmWR2
    keySecret: 15jL5aIAMZgAi3OHzkj92Bc8PyxCCU
    templateCode: SMS_154950909
    signName: 阿里云短信测试